//ajouter une categorie 
POST http://localhost:3001/ajout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxOCwibm9tIjoibG9ibmEiLCJlbWFpbCI6ImxvYm5hQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFpCTGE1N3VqcXBxaEQ4SmlKQ2VCOU9pRWFyaWI3SEN5Uno5WlMybUcub2ZSR2xmSlV4N24uIiwicm9sZSI6IkFVVEhPUiJ9LCJpYXQiOjE2ODQ1NDc2MzIsImV4cCI6MTY4NDU1MTIzMn0.GfXxYyT-jtO-Vq-nJJFwkNnp13KVeYf7eorGgzMlY9o

{
  "nom": "Nouvelle catégorie"
}
// Récupérer tous les categories avec pagination

GET http://localhost:3001/pagcategorie?take=30&skip=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxOSwibm9tIjoiaW1hZHN1cGVyYWRtaW4iLCJlbWFpbCI6ImltYWRhaW1hZDQwM0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuZ2FOSTgzRDVjYy54VUpMNGdrWTQuLkFPTmpTMXY5cWo2bU1oWTl1NnAwNlBhazFVeVlnVyIsInJvbGUiOiJBRE1JTiJ9LCJpYXQiOjE2ODQ2MTIzNzcsImV4cCI6MTY4NTg5Mzk3N30.C_7PFmAwwI5jfxrQ-DmAjgtnx3AQSrg0PFytqMc4MpM
 
// Récupérer une catégorie par son ID

GET http://localhost:3001/categorieid/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxOSwibm9tIjoiaW1hZHN1cGVyYWRtaW4iLCJlbWFpbCI6ImltYWRhaW1hZDQwM0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuZ2FOSTgzRDVjYy54VUpMNGdrWTQuLkFPTmpTMXY5cWo2bU1oWTl1NnAwNlBhazFVeVlnVyIsInJvbGUiOiJBRE1JTiJ9LCJpYXQiOjE2ODQ2MTIzNzcsImV4cCI6MTY4NTg5Mzk3N30.C_7PFmAwwI5jfxrQ-DmAjgtnx3AQSrg0PFytqMc4MpM



// mettre a jour par son id 
PATCH http://localhost:3001/miscategorie
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxOSwibm9tIjoiaW1hZHN1cGVyYWRtaW4iLCJlbWFpbCI6ImltYWRhaW1hZDQwM0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuZ2FOSTgzRDVjYy54VUpMNGdrWTQuLkFPTmpTMXY5cWo2bU1oWTl1NnAwNlBhazFVeVlnVyIsInJvbGUiOiJBRE1JTiJ9LCJpYXQiOjE2ODQ2MTIzNzcsImV4cCI6MTY4NTg5Mzk3N30.C_7PFmAwwI5jfxrQ-DmAjgtnx3AQSrg0PFytqMc4MpM

{
  "id": 2,
  "nom": "web 2"
}

//supprimer une categorie par son id

DELETE http://localhost:3001/deleteategorie/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxOSwibm9tIjoiaW1hZHN1cGVyYWRtaW4iLCJlbWFpbCI6ImltYWRhaW1hZDQwM0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuZ2FOSTgzRDVjYy54VUpMNGdrWTQuLkFPTmpTMXY5cWo2bU1oWTl1NnAwNlBhazFVeVlnVyIsInJvbGUiOiJBRE1JTiJ9LCJpYXQiOjE2ODQ2MTIzNzcsImV4cCI6MTY4NTg5Mzk3N30.C_7PFmAwwI5jfxrQ-DmAjgtnx3AQSrg0PFytqMc4MpM
